version: '3'

services:
  traefik:
    image: traefik:v2.10
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.prod.yml:/etc/traefik/traefik.yml
      - ./traefik/letsencrypt:/letsencrypt
      - ./traefik/logs:/opt/logs
    labels:
      - "traefik.http.middlewares.headers-cors.headers.accesscontrolalloworiginlist=https://app.babymonitor.creativeilk.com"
      - "traefik.http.middlewares.headers-cors.headers.accesscontrolallowheaders=Content-Type,Authorization"
      - "traefik.http.middlewares.headers-cors.headers.accesscontrolallowcredentials=true"

      - "traefik.http.middlewares.rate-limit-anonymous-token.ratelimit.average=1"
      - "traefik.http.middlewares.rate-limit-anonymous-token.ratelimit.period=20s"
      - "traefik.http.middlewares.rate-limit-anonymous-token.ratelimit.burst=1"

      - "traefik.http.middlewares.rate-limit-create-account.ratelimit.average=1"
      - "traefik.http.middlewares.rate-limit-create-account.ratelimit.period=20s"
      - "traefik.http.middlewares.rate-limit-create-account.ratelimit.burst=1"

      - "traefik.http.middlewares.rate-limit-options.ratelimit.average=1"
      - "traefik.http.middlewares.rate-limit-options.ratelimit.period=1s"
      - "traefik.http.middlewares.rate-limit-options.ratelimit.burst=4"

      - "traefik.http.middlewares.rate-limit-backend.ratelimit.average=1"
      - "traefik.http.middlewares.rate-limit-backend.ratelimit.period=1s"
      - "traefik.http.middlewares.rate-limit-backend.ratelimit.burst=4"
  backend:
    image: baby-monitor-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENCRYPTION_KEY=
      - APP_URL=https://app.babymonitor.creativeilk.com
      - SERVER_ADDR=:8000
      - ACCOUNT_STORE_IMPLEMENTATION=s3
      - ACCOUNT_STORE_S3_REGION=
      - ACCOUNT_STORE_S3_BUCKET=
    labels:
      - "traefik.http.routers.anonymous-token.rule=Host(`api.babymonitor.local`) && Path(`/anonymous_token`) && Method(`POST`)"
      - "traefik.http.routers.anonymous-token.entrypoints=websecure"
      - "traefik.http.routers.anonymous-token.tls=true"
      - "traefik.http.routers.anonymous-token.tls.certresolver=letsencrypt"
      - "traefik.http.routers.anonymous-token.tls.domains[0].main=api.babymonitor.creativeilk.com"
      - "traefik.http.routers.anonymous-token.middlewares=headers-cors@docker,rate-limit-anonymous-token@docker"

      - "traefik.http.routers.create-account.rule=Host(`api.babymonitor.local`) && Path(`/accounts`) && Method(`POST`)"
      - "traefik.http.routers.create-account.entrypoints=websecure"
      - "traefik.http.routers.create-account.tls=true"
      - "traefik.http.routers.create-account.tls.certresolver=letsencrypt"
      - "traefik.http.routers.create-account.tls.domains[0].main=api.babymonitor.creativeilk.com"
      - "traefik.http.routers.create-account.middlewares=headers-cors@docker,rate-limit-create-account@docker"

      - "traefik.http.routers.backend-options.rule=Host(`api.babymonitor.local`) && Method(`OPTIONS`)"
      - "traefik.http.routers.backend-options.entrypoints=websecure"
      - "traefik.http.routers.backend-options.tls=true"
      - "traefik.http.routers.backend-options.tls.certresolver=letsencrypt"
      - "traefik.http.routers.backend-options.tls.domains[0].main=api.babymonitor.creativeilk.com"
      - "traefik.http.routers.backend-options.middlewares=headers-cors@docker,rate-limit-options@docker"

      - "traefik.http.routers.backend.rule=Host(`api.babymonitor.creativeilk.com`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.backend.tls.domains[0].main=api.babymonitor.creativeilk.com"
      - "traefik.http.routers.backend.middlewares=headers-cors@docker,rate-limit-backend@docker"
