version: '3'

services:
  traefik:
    image: traefik:v2.10
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.local.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic_conf.local.yml:/etc/traefik/dynamic_conf.yml
      - ./traefik/certificates:/opt/certificates
    labels:
      - "traefik.http.middlewares.headers-cors.headers.accesscontrolalloworiginlist=https://app.babymonitor.local"
      - "traefik.http.middlewares.headers-cors.headers.accesscontrolallowheaders=Content-Type,Authorization"
      - "traefik.http.middlewares.headers-cors.headers.accesscontrolallowcredentials=true"
      - "traefik.http.middlewares.headers-cors.headers.accessControlAllowMethods=GET,OPTIONS,POST,PUT,DELETE"
    networks:
      default:
        aliases:
          - app.babymonitor.local
          - api.babymonitor.local
          - influx.babymonitor.local
          - grafana.babymonitor.local
  backend:
    image: baby-monitor-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - COOKIE_DOMAIN=.babymonitor.local
      - SERVER_ADDR=:8000
      - FILE_EVENT_LOG_FOLDER_PATH=/opt/eventlog
      - SQUARE_SCHEME=https
      - SQUARE_HOST=connect.squareupsandbox.com
      - SQUARE_APPLICATION_ID=${SQUARE_APPLICATION_ID}
      - SQUARE_ACCESS_TOKEN=${SQUARE_ACCESS_TOKEN}
      - SQUARE_SUBSCRIPTION_PLAN_ID=${SQUARE_SUBSCRIPTION_PLAN_ID}
      - SQUARE_LOCATION_ID=${SQUARE_LOCATION_ID}
      - SQUARE_SIGNATURE_KEY=${SQUARE_SIGNATURE_KEY}
    labels:
      - "traefik.http.routers.backend.rule=Host(`api.babymonitor.local`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.middlewares=headers-cors@docker"
  frontend:
    image: node:18
    command: yarn start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/opt/frontend
    environment:
      - WDS_SOCKET_HOST=app.babymonitor.local
      - WDS_SOCKET_PORT=443
    working_dir: /opt/frontend
    labels:
      - "traefik.http.routers.frontend.rule=Host(`app.babymonitor.local`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
  influxdb:
    image: influxdb:2.7-alpine
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
    labels:
      - "traefik.http.routers.influx.rule=Host(`influx.babymonitor.local`)"
      - "traefik.http.routers.influx.entrypoints=websecure"
      - "traefik.http.routers.influx.tls=true"
      - "traefik.http.routers.influx.middlewares=headers-cors@docker"
  grafana:
    image: grafana/grafana-oss:10.2.2
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
    labels:
      - "traefik.http.routers.grafana.rule=Host(`grafana.babymonitor.local`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.middlewares=headers-cors@docker"
  selenium_hub:
    image: selenium/hub:4.11.0-20230801
    restart: always
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  # selenium_firefox_node:
  #   image: selenium/node-firefox:4.11.0-20230801
  #   restart: always
  #   depends_on:
  #     - selenium_hub
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium_hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  selenium_chrome_node:
    image: selenium/node-chrome:4.11.0-20230801
    restart: always
    depends_on:
      - selenium_hub
    environment:
      - SE_EVENT_BUS_HOST=selenium_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    deploy:
      replicas: 2
  integration_tests:
    build: integration_tests
    volumes:
      - ./integration_tests/src:/usr/src/integration_tests
    working_dir: /usr/src/integration_tests
    command: tail -f /dev/null

volumes:
  # TODO influx_storage + set up script
  grafana_storage:

secrets:
  ENCRYPTION_KEY:
    external: true
  SQUARE_APPLICATION_ID:
    external: true
  SQUARE_ACCESS_TOKEN:
    external: true
  SQUARE_SUBSCRIPTION_PLAN_ID:
    external: true
  SQUARE_LOCATION_ID:
    external: true
  SQUARE_SIGNATURE_KEY:
    external: true
