version: '3'

services:
  reverse-proxy:
    image: traefik:v2.10
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.prod.yml:/etc/traefik/traefik.yml
      - ./traefik/letsencrypt:/letsencrypt
      - ./access.log:/opt/access.log
  backend:
    image: baby-monitor-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENCRYPTION_KEY=
      - APP_URL=https://app.babymonitor.creativeilk.com
      - SERVER_ADDR=:8000
      - ACCOUNT_STORE_IMPLEMENTATION=s3
      - ACCOUNT_STORE_S3_REGION=
      - ACCOUNT_STORE_S3_BUCKET=
    labels:
      - "traefik.http.routers.backend.rule=Host(`api.babymonitor.creativeilk.com`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.backend.tls.domains[0].main=api.babymonitor.creativeilk.com"