version: '3'

services:
  traefik:
    image: traefik:v2.10
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
      - "9000:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.local.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic_conf.local.yml:/etc/traefik/dynamic_conf.yml
      - ./traefik/certificates:/opt/certificates
    labels:
      - "traefik.http.middlewares.headers-cors.headers.accesscontrolalloworiginlist=https://app.babymonitor.local:8443"
      - "traefik.http.middlewares.headers-cors.headers.accesscontrolallowheaders=Content-Type,Authorization"
      - "traefik.http.middlewares.headers-cors.headers.accesscontrolallowcredentials=true"
      
      - "traefik.http.middlewares.rate-limit-anonymous-token.ratelimit.average=1"
      - "traefik.http.middlewares.rate-limit-anonymous-token.ratelimit.period=10s"
      - "traefik.http.middlewares.rate-limit-anonymous-token.ratelimit.burst=1"

      - "traefik.http.middlewares.rate-limit-create-account.ratelimit.average=1"
      - "traefik.http.middlewares.rate-limit-create-account.ratelimit.period=10s"
      - "traefik.http.middlewares.rate-limit-create-account.ratelimit.burst=1"

      - "traefik.http.middlewares.rate-limit-options.ratelimit.average=1"
      - "traefik.http.middlewares.rate-limit-options.ratelimit.period=1s"
      - "traefik.http.middlewares.rate-limit-options.ratelimit.burst=5"

      - "traefik.http.middlewares.rate-limit-backend.ratelimit.average=1"
      - "traefik.http.middlewares.rate-limit-backend.ratelimit.period=1s"
      - "traefik.http.middlewares.rate-limit-backend.ratelimit.burst=5"
  backend:
    image: baby-monitor-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./account_store:/opt/account_store
    environment:
      - ENCRYPTION_KEY=passwordpasswordpasswordpassword
      - COOKIE_DOMAIN=.babymonitor.local
      - SERVER_ADDR=:8000
      - SQUARE_SIGNATURE_KEY=password
    labels:
      - "traefik.http.routers.anonymous-token.rule=Host(`api.babymonitor.local`) && Path(`/anonymous_token`) && Method(`POST`)"
      - "traefik.http.routers.anonymous-token.entrypoints=websecure"
      - "traefik.http.routers.anonymous-token.tls=true"
      - "traefik.http.routers.anonymous-token.middlewares=headers-cors@docker,rate-limit-anonymous-token@docker"

      - "traefik.http.routers.create-account.rule=Host(`api.babymonitor.local`) && Path(`/accounts`) && Method(`POST`)"
      - "traefik.http.routers.create-account.entrypoints=websecure"
      - "traefik.http.routers.create-account.tls=true"
      - "traefik.http.routers.create-account.middlewares=headers-cors@docker,rate-limit-create-account@docker"

      - "traefik.http.routers.backend-options.rule=Host(`api.babymonitor.local`) && Method(`OPTIONS`)"
      - "traefik.http.routers.backend-options.entrypoints=websecure"
      - "traefik.http.routers.backend-options.tls=true"
      - "traefik.http.routers.backend-options.middlewares=headers-cors@docker,rate-limit-options@docker"

      - "traefik.http.routers.backend.rule=Host(`api.babymonitor.local`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.middlewares=headers-cors@docker,rate-limit-backend@docker"
  frontend:
    image: node:18
    command: yarn start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/opt/frontend
    environment:
      - WDS_SOCKET_HOST=app.babymonitor.local
      - WDS_SOCKET_PORT=8443
    working_dir: /opt/frontend
    labels:
      - "traefik.http.routers.frontend.rule=Host(`app.babymonitor.local`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
  influxdb:
    image: influxdb:2.7-alpine
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb2