providers:
  docker: {}

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

certificatesResolvers:
  letsencrypt:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: ${EMAIL}
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

log:
  level: WARN

accessLog:
  filePath: /opt/logs/access.log
  bufferingSize: 128