version: '3'

services:
  hub:
    image: selenium/hub:4.11.0-20230801
    restart: always
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  firefox:
    image: selenium/node-firefox:4.11.0-20230801
    restart: always
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  chrome:
    image: selenium/node-chrome:4.11.0-20230801
    restart: always
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  script:
    build: .
    depends_on:
      - firefox
      - chrome
    volumes:
      - ./scripts:/scripts
    working_dir: /scripts
    command: tail -f /dev/null
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}

secrets:
  EMAIL:
    external: true
  PASSWORD:
    external: true
